create database IT_Support_Analysis;
use IT_Support_Analysis;
select * from Employees;
select count(*) as Total_rows from tickets;
select * from departments;
select * from Tickets;
select * from ticket_history;
select * from support_engineers;
describe employees;
describe departments;

select joining_date from employees limit 5;

select joining_date,cast(joining_date as date) as new_joining_date from employees limit 10;
alter table employees modify joining_date date;
select * from employees where employee_id is null or employee_name is null or department is null or joining_date is null; 
select employee_id,count(*) as count from employees group by employee_id having count(*)>1;
select employee_name,count(*) as count from employees group by employee_name having count(*)>1;
select e.department from employees e left join departments d on e.employee_id = d.department_id where d.department_id is null;
select * from employees where joining_date >curdate();
select * from employees where employee_name is null or trim(employee_name) = '';
select  * from employees where employee_name is null or employee_name not regexp '^[A-Za-z ]+$' ;
select * from employees where employee_id is null or employee_id<=0;
select * from employees where department is null or department<=0;
select * from employees where joining_date is null;
select distinct(employee_id) from employees;
select employee_id,count(*) as count from employees group by employee_id having count(*) >1;
select t.employee_id from tickets t left join employees e on t.employee_id = e.employee_id where e.employee_id is null;
select ticket_id,count(*) as count from tickets group by ticket_id having count(*) >1;
select * from tickets;
select * from tickets where ticket_id is null or employee_id is null or category is null or created_date is null or issue_type is null or created_date is null or resolved_date is null or status is null or assigned_to is null or resolution_time_hours or priority is null; 
select distinct(priority) from tickets; 
select distinct(status) from tickets; 
select * from tickets where created_date = now();
select * from support_engineers;
describe support_engineers;
select t.ticket_id,t.employee_id,t.category,t.priority,t.issue_type,t.created_date,t.resolved_date,t.status,t.assigned_to,s.engineer_name,s.team,s.experience_years from tickets t left join support_engineers s on t.assigned_to = s.engineer_id;
describe employees;
describe tickets;
select e.employee_name,t.ticket_id,t.employee_id,t.category,t.priority,t.issue_type,t.created_date,t.resolved_date,t.status,t.assigned_to,s.engineer_name,s.team,s.experience_years from tickets t left join employees e on t.employee_id=e.employee_id left join support_engineers s on t.assigned_to = s.engineer_id;
select priority,count(*) as ticketcount from tickets group by priority order by ticketcount desc;
select status,count(*) as ticketcount from tickets group by status order by ticketcount desc;
select category,count(*) as ticketcount from tickets group by category order by ticketcount desc;
select count(*) as totat_tickets,sum(ticket_id is null) as Nullticketid,sum(employee_id is null) as nullemployee_id, sum(category is null) as nullcategory,
sum(priority is null) as Nullpriority,sum(issue_type is null) as nullissue, sum(created_date is null) as nullcreate,
sum(resolved_date is null) as Nullresolved,sum(status is null) as nullstatus, sum(assigned_to is null) as nullassigned,sum(resolution_time_hours is null) as time from tickets;
select ticket_id,count(*) as ticketduplicate from tickets group by ticket_id having count(*) >1;
select distinct (t.employee_id) from tickets t left join employees e on t.employee_id=e.employee_id where e.employee_id is null;
select distinct (t.assigned_to) from tickets t left join support_engineers s on t.assigned_to=s.engineer_id where s.engineer_id is null;
select * from tickets where resolved_date < created_date;
select * from tickets where resolution_time_hours <0;
select round(avg(resolution_time_hours),2) as avgtime from tickets;
select  priority,count(*) as ticketcount,round(avg(resolution_time_hour), 2) as avgresolution from tickrts group by priority order by avgresolution;
select issue_type,count(*) as ticketcount from tickets group by issue_type order by ticketcount desc;
select year(created_date) as year,month(created_date) as month,count(*) as ticketcount from tickets group by  year(created_date),month(created_date) order by year,month;
select ticket_id,created_date,resolved_date,status,resolution_time_hours from tickets where resolved_date <created_date;
select status,count(*) as count from tickets where resolved_date <created_date group by status;
select priority,count(*) as ticketcount,round(avg(cast(resolution_time_hours as decimal(10,2))),2) as avgresolutiontime from tickets group by priority order by avgresolutiontime desc;
select s.engineer_id,s.engineer_name,count(t.ticket_id) as Totaltickets,round(avg(t.resolution_time_hours),2) as avgresolutiontime from tickets t left join support_engineers s on t.assigned_to = s.engineer_id group by s.engineer_id,s.engineer_name order by totaltickets desc;
select e.department,count(t.ticket_id) as ticketcount from tickets t left join employees e on t.employee_id = e.employee_id group by e.department order by ticketcount desc; 
select year(created_date) as year, month(created_date) as month,count(*) as ticketcount from tickets group by year(created_date),month(created_date) order by year,month;
select priority,status,count(*) as ticketcount from tickets group by priority,status order by priority,ticketcount desc;
select category,count(*) as ticketcount,round(avg(resolution_time_hours),2) as avgresolutiontime from tickets group by category order by avgresolutiontime desc;
select count(*) as totaltickets,sum(case when status = 'Resolved' then 1 else 0 end) as resolved_tickets,sum(case when status = 'open' then 1 else 0 end) as opentickets, sum(case when status ='pending' then 1 else 0 end) as pendingtickets from tickets;